# Generated by Django 5.1 on 2025-02-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todos",
            name="due_date",
            field=models.DateField(),
        ),
    ]
