# Generated by Django 5.1 on 2025-02-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_alter_todos_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="todos",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
