# Generated by Django 5.1 on 2025-02-19 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_todos_is_completed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedules",
            name="user",
            field=models.ManyToManyField(
                related_name="schedules", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
