# Generated by Django 5.1 on 2025-03-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_schedulenotification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScheduleNotification",
        ),
    ]
