# Generated by Django 5.1 on 2025-01-26 09:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatsGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_category",
                    models.IntegerField(
                        choices=[
                            (1, "共有チャット"),
                            (2, "グループチャット"),
                            (3, "個人チャット"),
                        ]
                    ),
                ),
                ("groupname", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="chat_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "chats_groups",
            },
        ),
        migrations.CreateModel(
            name="Chats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("picture", models.FileField(null=True, upload_to="chats_picture/")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chatsgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="chats.chatsgroups",
                    ),
                ),
            ],
            options={
                "db_table": "chats",
            },
        ),
    ]
