# Generated by Django 5.1 on 2025-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_chatsgroup_alter_chats_chatsgroup_delete_chatsgroups"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsgroup",
            name="picture",
            field=models.FileField(
                default="group_picture/no_image.jpeg",
                null=True,
                upload_to="group_picture/",
            ),
        ),
    ]
