# Generated by Django 5.1 on 2025-07-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_chatsgroup_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chats",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
