# Generated by Django 5.1 on 2025-03-17 15:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_webpushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpushsubscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 3, 17, 15, 11, 53, 244175, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="webpushsubscription",
            name="auth_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="webpushsubscription",
            name="endpoint",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="webpushsubscription",
            name="p256dh_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="webpushsubscription",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
