# Generated by Django 5.1 on 2025-03-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_webpushsubscription_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="webpushsubscription",
            table="webpush_subscription",
        ),
    ]
