# Generated by Django 5.1 on 2025-03-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_webpushsubscription_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpushsubscription",
            name="data",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
