# Generated by Django 5.1 on 2025-03-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_webpushsubscription_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpushsubscription",
            name="auth_key",
            field=models.CharField(default="default_key", max_length=255),
        ),
        migrations.AlterField(
            model_name="webpushsubscription",
            name="p256dh_key",
            field=models.CharField(default="default_key", max_length=255),
            preserve_default=False,
        ),
    ]
