# Generated by Django 5.1 on 2025-03-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_webpushsubscription_auth_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webpushsubscription",
            name="auth_key",
        ),
        migrations.RemoveField(
            model_name="webpushsubscription",
            name="data",
        ),
    ]
