# Generated by Django 5.1 on 2025-04-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_webpushsubscription_auth_key_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
