# Generated by Django 5.1 on 2025-07-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_rename_update_at_users_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebPushSubscription",
        ),
    ]
