# Generated by Django 5.1 on 2025-07-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_delete_webpushsubscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_active",
        ),
        migrations.DeleteModel(
            name="UserActivateTokens",
        ),
    ]
