# Generated by Django 5.1 on 2025-07-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_users_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="is_active",
            new_name="notification_sent",
        ),
    ]
