# Generated by Django 5.1 on 2025-08-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_rename_is_active_users_notification_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="hurigana",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
