# Generated by Django 5.1 on 2025-10-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_users_hurigana"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="last_notificated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
