# Generated by Django 5.1 on 2025-10-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_users_last_notificated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="notification_sent",
        ),
    ]
