# Generated by Django 5.1 on 2025-10-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_users_notification_sent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="last_notificated",
            new_name="last_notificated",
        ),
    ]
