# Generated by Django 5.1 on 2025-08-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="picture",
            field=models.FileField(
                default="question_picture/no_Image.jpg",
                null=True,
                upload_to="question_picture/",
            ),
        ),
    ]
