# Generated by Django 5.1 on 2025-08-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_alter_questions_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="picture",
            field=models.FileField(
                default="answer_picture/no_Image.jpg",
                null=True,
                upload_to="answer_picture/",
            ),
        ),
    ]
